// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TestBasesColumns holds the columns for the "test_bases" table.
	TestBasesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "parent_id", Type: field.TypeUUID, Nullable: true},
		{Name: "name", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "created_at", Type: field.TypeInt64, Nullable: true, Default: 1710574697677},
		{Name: "updated_at", Type: field.TypeInt64, Nullable: true, Default: 1710574697677},
		{Name: "deleted_at", Type: field.TypeInt64, Nullable: true},
		{Name: "version", Type: field.TypeInt, Nullable: true, Default: 0},
		{Name: "text", Type: field.TypeString, Nullable: true, Size: 255},
	}
	// TestBasesTable holds the schema information for the "test_bases" table.
	TestBasesTable = &schema.Table{
		Name:       "test_bases",
		Columns:    TestBasesColumns,
		PrimaryKey: []*schema.Column{TestBasesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "testbase_name_id",
				Unique:  false,
				Columns: []*schema.Column{TestBasesColumns[2], TestBasesColumns[0]},
			},
			{
				Name:    "testbase_deleted_at_id",
				Unique:  false,
				Columns: []*schema.Column{TestBasesColumns[5], TestBasesColumns[0]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TestBasesTable,
	}
)

func init() {
}
