// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	dbmodel "github.com/chroma-core/chroma/go/pkg/sysdb/metastore/db/dbmodel"
	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// IAttachedFunctionDb is an autogenerated mock type for the IAttachedFunctionDb type
type IAttachedFunctionDb struct {
	mock.Mock
}

// CleanupExpiredPartial provides a mock function with given fields: maxAgeSeconds
func (_m *IAttachedFunctionDb) CleanupExpiredPartial(maxAgeSeconds uint64) ([]uuid.UUID, error) {
	ret := _m.Called(maxAgeSeconds)

	if len(ret) == 0 {
		panic("no return value specified for CleanupExpiredPartial")
	}

	var r0 []uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) ([]uuid.UUID, error)); ok {
		return rf(maxAgeSeconds)
	}
	if rf, ok := ret.Get(0).(func(uint64) []uuid.UUID); ok {
		r0 = rf(maxAgeSeconds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(maxAgeSeconds)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteAll provides a mock function with no fields
func (_m *IAttachedFunctionDb) DeleteAll() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DeleteAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Finish provides a mock function with given fields: id
func (_m *IAttachedFunctionDb) Finish(id uuid.UUID) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Finish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAttachedFunctions provides a mock function with given fields: id, name, inputCollectionID, onlyReady
func (_m *IAttachedFunctionDb) GetAttachedFunctions(id *uuid.UUID, name *string, inputCollectionID *string, onlyReady bool) ([]*dbmodel.AttachedFunction, error) {
	ret := _m.Called(id, name, inputCollectionID, onlyReady)

	if len(ret) == 0 {
		panic("no return value specified for GetAttachedFunctions")
	}

	var r0 []*dbmodel.AttachedFunction
	var r1 error
	if rf, ok := ret.Get(0).(func(*uuid.UUID, *string, *string, bool) ([]*dbmodel.AttachedFunction, error)); ok {
		return rf(id, name, inputCollectionID, onlyReady)
	}
	if rf, ok := ret.Get(0).(func(*uuid.UUID, *string, *string, bool) []*dbmodel.AttachedFunction); ok {
		r0 = rf(id, name, inputCollectionID, onlyReady)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dbmodel.AttachedFunction)
		}
	}

	if rf, ok := ret.Get(1).(func(*uuid.UUID, *string, *string, bool) error); ok {
		r1 = rf(id, name, inputCollectionID, onlyReady)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMinCompletionOffsetForCollection provides a mock function with given fields: inputCollectionID
func (_m *IAttachedFunctionDb) GetMinCompletionOffsetForCollection(inputCollectionID string) (*int64, error) {
	ret := _m.Called(inputCollectionID)

	if len(ret) == 0 {
		panic("no return value specified for GetMinCompletionOffsetForCollection")
	}

	var r0 *int64
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*int64, error)); ok {
		return rf(inputCollectionID)
	}
	if rf, ok := ret.Get(0).(func(string) *int64); ok {
		r0 = rf(inputCollectionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*int64)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(inputCollectionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSoftDeletedAttachedFunctions provides a mock function with given fields: cutoffTime, limit
func (_m *IAttachedFunctionDb) GetSoftDeletedAttachedFunctions(cutoffTime time.Time, limit int32) ([]*dbmodel.AttachedFunction, error) {
	ret := _m.Called(cutoffTime, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetSoftDeletedAttachedFunctions")
	}

	var r0 []*dbmodel.AttachedFunction
	var r1 error
	if rf, ok := ret.Get(0).(func(time.Time, int32) ([]*dbmodel.AttachedFunction, error)); ok {
		return rf(cutoffTime, limit)
	}
	if rf, ok := ret.Get(0).(func(time.Time, int32) []*dbmodel.AttachedFunction); ok {
		r0 = rf(cutoffTime, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dbmodel.AttachedFunction)
		}
	}

	if rf, ok := ret.Get(1).(func(time.Time, int32) error); ok {
		r1 = rf(cutoffTime, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HardDeleteAttachedFunction provides a mock function with given fields: id
func (_m *IAttachedFunctionDb) HardDeleteAttachedFunction(id uuid.UUID) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for HardDeleteAttachedFunction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Insert provides a mock function with given fields: attachedFunction
func (_m *IAttachedFunctionDb) Insert(attachedFunction *dbmodel.AttachedFunction) error {
	ret := _m.Called(attachedFunction)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*dbmodel.AttachedFunction) error); ok {
		r0 = rf(attachedFunction)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SoftDelete provides a mock function with given fields: inputCollectionID, name
func (_m *IAttachedFunctionDb) SoftDelete(inputCollectionID string, name string) error {
	ret := _m.Called(inputCollectionID, name)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(inputCollectionID, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SoftDeleteByID provides a mock function with given fields: id, inputCollectionID
func (_m *IAttachedFunctionDb) SoftDeleteByID(id uuid.UUID, inputCollectionID uuid.UUID) error {
	ret := _m.Called(id, inputCollectionID)

	if len(ret) == 0 {
		panic("no return value specified for SoftDeleteByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(id, inputCollectionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: attachedFunction
func (_m *IAttachedFunctionDb) Update(attachedFunction *dbmodel.AttachedFunction) error {
	ret := _m.Called(attachedFunction)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*dbmodel.AttachedFunction) error); ok {
		r0 = rf(attachedFunction)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIAttachedFunctionDb creates a new instance of IAttachedFunctionDb. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAttachedFunctionDb(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAttachedFunctionDb {
	mock := &IAttachedFunctionDb{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
