CREATE TABLE IF NOT EXISTS databases (
    ID STRING(MAX) NOT NULL,
    NAME STRING(MAX) NOT NULL,
    TENANT_ID STRING(MAX) NOT NULL,
    IS_DELETED BOOL DEFAULT (false),
    CREATED_AT TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp=true),
    UPDATED_AT TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp=true),
) PRIMARY KEY (ID)