export default function Test() {
  return (
    <div className="p-20">
      <div className="sticky top-0">Test 1</div>
      <div>Test 2</div>
      <div>Test 3</div>
      <div>Test 4</div>
      <div>Test 5</div>
      <div>Test 6</div>
      <div>Test 7</div>
      <div>Test 8</div>
      <div>Test 9</div>
      <div>Test 10</div>
      <div>Test 11</div>
      <div>Test 12</div>
      <div>Test 13</div>
      <div>Test 14</div>
      <div>Test 15</div>
      <div>Test 16</div>
      <div>Test 17</div>
      <div>Test 18</div>
      <div>Test 19</div>
      <div>Test 20</div>
      <div>Test 21</div>
      <div>Test 22</div>
      <div>Test 23</div>
      <div>Test 24</div>
      <div>Test 25</div>
      <div>Test 26</div>
      <div>Test 27</div>
      <div>Test 28</div>
      <div>Test 29</div>
      <div>Test 30</div>
      <div>Test 31</div>
      <div>Test 32</div>
      <div>Test 33</div>
      <div>Test 34</div>
      <div>Test 35</div>
      <div>Test 36</div>
      <div>Test 37</div>
      <div>Test 38</div>
      <div>Test 39</div>
      <div>Test 40</div>
      <div>Test 41</div>
      <div>Test 42</div>
      <div>Test 43</div>
      <div>Test 44</div>
      <div>Test 45</div>
      <div>Test 46</div>
      <div>Test 47</div>
      <div>Test 48</div>
      <div>Test 49</div>
      <div>Test 50</div>
      <div>Test 51</div>
      <div>Test 52</div>
      <div>Test 53</div>
      <div>Test 54</div>
      <div>Test 55</div>
      <div>Test 56</div>
      <div>Test 57</div>
      <div>Test 58</div>
      <div>Test 59</div>
      <div>Test 60</div>
      <div>Test 61</div>
      <div>Test 62</div>
      <div>Test 63</div>
      <div>Test 64</div>
      <div>Test 65</div>
      <div>Test 66</div>
      <div>Test 67</div>
      <div>Test 68</div>
      <div>Test 69</div>
      <div>Test 70</div>
      <div>Test 71</div>
      <div>Test 72</div>
      <div>Test 73</div>
      <div>Test 74</div>
      <div>Test 75</div>
      <div>Test 76</div>
      <div>Test 77</div>
      <div>Test 78</div>
      <div>Test 79</div>
      <div>Test 80</div>
      <div>Test 81</div>
      <div>Test 82</div>
      <div>Test 83</div>
      <div>Test 84</div>
      <div>Test 85</div>
      <div>Test 86</div>
      <div>Test 87</div>
      <div>Test 88</div>
      <div>Test 89</div>
      <div>Test 90</div>
      <div>Test 91</div>
      <div>Test 92</div>
      <div>Test 93</div>
      <div>Test 94</div>
      <div>Test 95</div>
      <div>Test 96</div>
      <div>Test 97</div>
      <div>Test 98</div>
      <div>Test 99</div>
      <div>Test 100</div>
    </div>
  );
}
