project_id                      = "your-gcp-project-id"
region                          = "your-region" # e.g., "us-central1"
zone                            = "your-zone"
machine_type                    = ""
chroma_version                  = "1.3.5"
chroma_otel_collection_endpoint = ""
chroma_otel_service_name        = ""
chroma_otel_collection_headers  = ""
