import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react";
import Header from "@/components/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`h-full w-full overflow-hidden ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="relative h-full w-full">
          <div className="absolute inset-0 bg-[url('/background.jpg')] bg-cover bg-center opacity-10" />
          <div className="relative z-10 flex flex-col h-full">
            <Header />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
