// This file is auto-generated by @hey-api/openapi-ts

/**
 * Auto-sync mode for S3 sources
 * - `none`: Manual invocations only (default, only supported mode initially)
 * - `direct`: Triggered by S3 events (future)
 * - `metadata`: Triggered by S3 events with custom metadata support (future)
 */
export type AutoSync = 'none' | 'direct' | 'metadata';

export type CancelJobResponse = {
    [key: string]: unknown;
};

export type CreateJobPayload = {
    /**
     * Custom ID for Chroma object IDs (optional, S3 sources only).
     * If provided, chunk IDs become "custom_id-{chunk}" instead of "sha256(object_key)-{chunk}".
     * Also stored as "custom_id" metadata on each chunk.
     */
    custom_id?: string | null;
    /**
     * Additional metadata to merge with standard chunk metadata (optional, S3 sources only).
     */
    metadata?: {
        [key: string]: unknown;
    } | null;
    /**
     * Full S3 object key to sync (required for S3 sources, not allowed for other source types).
     * Must be the complete key including any path prefix configured on the source.
     */
    object_key?: string | null;
    ref_identifier?: null | GitRefIdentifier;
    /**
     * Target collection name (optional for S3 sources, required for others).
     * For S3 sources: if not provided, uses collection_name from source config.
     * For GitHub and WebScrape sources: required.
     */
    target_collection_name?: string | null;
};

export type CreateJobResponse = {
    /**
     * ID of the newly created invocation
     */
    invocation_id: JobId;
};

export type CreateSourcePayload = SourceType & {
    /**
     * Optional chunking configuration for this source.
     */
    chunking?: SourceChunkingConfig;
    database_name: string;
    embedding?: SourceEmbeddingConfig;
    embedding_model?: null | DenseEmbeddingModel;
};

export type CreateSourceResponse = {
    /**
     * Source ID
     */
    source_id: SourceId;
};

export type DenseEmbeddingConfig = DenseEmbeddingModel;

export type DenseEmbeddingModel = {
    model: 'Qwen/Qwen3-Embedding-0.6B';
    task?: null | Qwen3EmbeddingTask;
};

export type ErrorResponse = {
    error: string;
    message: string;
};

export type GitRefIdentifier = {
    sha: string;
} | {
    branch: string;
};

export type HashMap = {
    [key: string]: {
        created_at: string;
        id: JobId;
        metadata: IndexJobMetadata;
        source_id?: null | SourceId;
        status: JobStatus;
    };
};

export type IndexJobMetadata = IndexJobMetadataKind & {
    collection_name: string;
    database_name: string;
};

export type IndexJobMetadataKind = 'web_scrape' | {
    github: {
        git_ref_identifier: GitRefIdentifier;
    };
} | {
    s3: {
        additional_metadata?: {
            [key: string]: unknown;
        } | null;
        bucket_name: string;
        custom_id?: string | null;
        object_key?: string | null;
    };
} | 'Unknown';

export type Job = {
    created_at: string;
    id: JobId;
    metadata: IndexJobMetadata;
    source_id?: null | SourceId;
    status: JobStatus;
};

export type JobId = string;

export type JobStatus = 'pending' | 'processing' | {
    complete: {
        duration_ms: number;
        finished_at: string;
    };
} | {
    failed: {
        error: string;
    };
} | 'cancelled';

export type LatestByKeysRequest = {
    object_keys: Array<string>;
};

export type Qwen3EmbeddingTask = {
    document_prompt?: string | null;
    query_prompt?: string | null;
    task_name: string;
};

export type Source = SourceType & {
    chunking: SourceChunkingConfig;
    created_at: string;
    database_name: string;
    embedding: SourceEmbeddingConfig;
    embedding_model: DenseEmbeddingModel;
    id: SourceId;
};

export type SourceChunkingConfig = {
    max_size_bytes?: number;
    type: 'tree_sitter';
} | {
    max_lines?: number;
    max_size_bytes?: number;
    type: 'lines';
};

export type SourceEmbeddingConfig = {
    dense?: DenseEmbeddingConfig;
    sparse?: null | SparseEmbeddingConfig;
};

export type SourceId = string;

export type SourceType = {
    github: {
        app_id?: string | null;
        include_globs?: Array<string> | null;
        repository: string;
    };
} | {
    web_scrape: {
        exclude_path_regexes?: Array<string> | null;
        include_path_regexes?: Array<string> | null;
        max_depth?: number | null;
        page_limit?: number | null;
        starting_url: string;
    };
} | {
    s3: {
        auto_sync?: null | AutoSync;
        /**
         * AWS credential ID for accessing the bucket.
         * Credentials must be created in Dashboard API first.
         */
        aws_credential_id: number;
        bucket_name: string;
        collection_name: string;
        path_prefix?: string | null;
        region: string;
    };
};

export type SparseEmbeddingConfig = {
    key?: string;
    model?: SparseEmbeddingModel;
};

export type SparseEmbeddingModel = 'Chroma/BM25' | 'prithivida/Splade_PP_en_v1';

export type Vec = Array<{
    created_at: string;
    id: JobId;
    metadata: IndexJobMetadata;
    source_id?: null | SourceId;
    status: JobStatus;
}>;

export type SourceTypeFilter = 'github' | 'web_scrape' | 's3';

export type OrderBy = 'ASC' | 'DESC';

export type ListJobsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Source ID. Cannot be provided simultaneously with database_name
         */
        source_id?: SourceId;
        /**
         * Database name. Cannot be provided simultaneously with source_id
         */
        database_name?: string;
        /**
         * Filter invocations by source type
         */
        source_type?: SourceTypeFilter;
        /**
         * Filter invocations by status
         */
        status?: JobStatus;
        /**
         * Limit for pagination. Default is 100
         */
        limit?: number;
        /**
         * Offset for pagination. Default is 0
         */
        offset?: number;
        /**
         * Order results by creation time. Default is DESC
         */
        order_by?: OrderBy;
    };
    url: '/api/v1/invocations';
};

export type ListJobsErrors = {
    /**
     * Bad request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Source not found
     */
    404: ErrorResponse;
    /**
     * Server error
     */
    500: ErrorResponse;
};

export type ListJobsError = ListJobsErrors[keyof ListJobsErrors];

export type ListJobsResponses = {
    /**
     * Found invocations
     */
    200: Vec;
};

export type ListJobsResponse = ListJobsResponses[keyof ListJobsResponses];

export type GetJobData = {
    body?: never;
    path: {
        /**
         * Invocation ID
         */
        invocation_id: JobId;
    };
    query?: never;
    url: '/api/v1/invocations/{invocation_id}';
};

export type GetJobErrors = {
    /**
     * Bad request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Invocation not found
     */
    404: ErrorResponse;
    /**
     * Server error
     */
    500: ErrorResponse;
};

export type GetJobError = GetJobErrors[keyof GetJobErrors];

export type GetJobResponses = {
    /**
     * Found invocation with provided ID
     */
    200: Job;
};

export type GetJobResponse = GetJobResponses[keyof GetJobResponses];

export type CancelPendingJobData = {
    body?: never;
    path: {
        /**
         * Invocation ID
         */
        invocation_id: JobId;
    };
    query?: never;
    url: '/api/v1/invocations/{invocation_id}';
};

export type CancelPendingJobErrors = {
    /**
     * Bad request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Invocation not found
     */
    404: ErrorResponse;
    /**
     * Invocation is not in a cancelable state
     */
    412: ErrorResponse;
    /**
     * Server error
     */
    500: ErrorResponse;
};

export type CancelPendingJobError = CancelPendingJobErrors[keyof CancelPendingJobErrors];

export type CancelPendingJobResponses = {
    /**
     * Invocation cancellation successful
     */
    202: CancelJobResponse;
};

export type CancelPendingJobResponse = CancelPendingJobResponses[keyof CancelPendingJobResponses];

export type ListSourcesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Database name
         */
        database_name?: string;
        /**
         * Filter sources by type
         */
        source_type?: SourceTypeFilter;
        /**
         * Limit for pagination. Default is 100
         */
        limit?: number;
        /**
         * Offset for pagination. Default is 0
         */
        offset?: number;
        /**
         * Order results by creation time. Default is DESC
         */
        order_by?: OrderBy;
    };
    url: '/api/v1/sources';
};

export type ListSourcesErrors = {
    /**
     * Bad request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Source not found
     */
    404: ErrorResponse;
    /**
     * Server error
     */
    500: ErrorResponse;
};

export type ListSourcesError = ListSourcesErrors[keyof ListSourcesErrors];

export type ListSourcesResponses = {
    /**
     * Found sources
     */
    200: Array<Source>;
};

export type ListSourcesResponse = ListSourcesResponses[keyof ListSourcesResponses];

export type CreateSourceData = {
    body: CreateSourcePayload;
    path?: never;
    query?: never;
    url: '/api/v1/sources';
};

export type CreateSourceErrors = {
    /**
     * Bad request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not found
     */
    404: ErrorResponse;
    /**
     * Source exists
     */
    409: ErrorResponse;
    /**
     * Server error
     */
    500: ErrorResponse;
};

export type CreateSourceError = CreateSourceErrors[keyof CreateSourceErrors];

export type CreateSourceResponses = {
    /**
     * Source creation successful
     */
    201: CreateSourceResponse;
};

export type CreateSourceResponse2 = CreateSourceResponses[keyof CreateSourceResponses];

export type DeleteSourceData = {
    body?: never;
    path: {
        /**
         * Source ID
         */
        source_id: SourceId;
    };
    query?: never;
    url: '/api/v1/sources/{source_id}';
};

export type DeleteSourceErrors = {
    /**
     * Bad request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Source not found
     */
    404: ErrorResponse;
    /**
     * Server error
     */
    500: ErrorResponse;
};

export type DeleteSourceError = DeleteSourceErrors[keyof DeleteSourceErrors];

export type DeleteSourceResponses = {
    /**
     * Source deletion successful
     */
    204: void;
};

export type DeleteSourceResponse = DeleteSourceResponses[keyof DeleteSourceResponses];

export type GetSourceData = {
    body?: never;
    path: {
        /**
         * Source ID
         */
        source_id: SourceId;
    };
    query?: never;
    url: '/api/v1/sources/{source_id}';
};

export type GetSourceErrors = {
    /**
     * Bad request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not found
     */
    404: ErrorResponse;
    /**
     * Server error
     */
    500: ErrorResponse;
};

export type GetSourceError = GetSourceErrors[keyof GetSourceErrors];

export type GetSourceResponses = {
    /**
     * Found source with provided ID
     */
    200: Source;
};

export type GetSourceResponse = GetSourceResponses[keyof GetSourceResponses];

export type CreateJobData = {
    body: CreateJobPayload;
    path: {
        /**
         * Source ID
         */
        source_id: SourceId;
    };
    query?: never;
    url: '/api/v1/sources/{source_id}/invocations';
};

export type CreateJobErrors = {
    /**
     * Bad request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Source not found
     */
    404: ErrorResponse;
    /**
     * Invocation exists
     */
    409: ErrorResponse;
    /**
     * Server error
     */
    500: ErrorResponse;
};

export type CreateJobError = CreateJobErrors[keyof CreateJobErrors];

export type CreateJobResponses = {
    /**
     * Invocation creation successful
     */
    201: CreateJobResponse;
};

export type CreateJobResponse2 = CreateJobResponses[keyof CreateJobResponses];

export type LatestInvocationsByKeysData = {
    body: LatestByKeysRequest;
    path: {
        /**
         * Source ID
         */
        source_id: SourceId;
    };
    query?: never;
    url: '/api/v1/sources/{source_id}/invocations/latest-by-keys';
};

export type LatestInvocationsByKeysErrors = {
    /**
     * Bad request
     */
    400: ErrorResponse;
    /**
     * Unauthorized
     */
    401: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Source not found
     */
    404: ErrorResponse;
    /**
     * Server error
     */
    500: ErrorResponse;
};

export type LatestInvocationsByKeysError = LatestInvocationsByKeysErrors[keyof LatestInvocationsByKeysErrors];

export type LatestInvocationsByKeysResponses = {
    /**
     * Latest invocation per object key
     */
    200: HashMap;
};

export type LatestInvocationsByKeysResponse = LatestInvocationsByKeysResponses[keyof LatestInvocationsByKeysResponses];

export type HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckErrors = {
    /**
     * Service is unavailable
     */
    503: unknown;
};

export type HealthCheckResponses = {
    /**
     * Health check successful
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};