apiVersion: v1
kind: ConfigMap
metadata:
  name: work-queue-config
data:
  config.yaml: |
    work_queue:
      enabled: false
      storage_path: "s3://chroma/work-queue/queue.parquet"
      persistence:
        time_threshold_seconds: 30
        operation_threshold: 100
        memory_threshold: 10000
      use_sysdb_filtering: false
      grpc_port: 50054
