from fastapi import FastAPI, Request
from typing import Union
from pathlib import Path
from fastapi.templating import Jinja2Templates
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse

def serve_react_app(app: FastAPI, build_dir: Union[Path, str]) -> FastAPI:
        """Serves a React application in the root directory `/`

        Args:
            app: FastAPI application instance
            build_dir: React build directory (generated by `yarn build` or
                `npm run build`)

        Returns:
            FastAPI: instance with the react application added
        """
        if isinstance(build_dir, str):
            build_dir = Path(build_dir)

        app.mount(
            "/static/",
            StaticFiles(directory=build_dir / "static"),
            name="React App static files",
        )
        templates = Jinja2Templates(directory=build_dir.as_posix())

        @app.get("/manifest.json")
        async def serve_manifest_json():
            """Serve the react app
            `full_path` variable is necessary to serve each possible endpoint with
            `index.html` file in order to be compatible with `react-router-dom
            """
            return FileResponse("static/manifest.json")

        @app.get("/{full_path:path}")
        async def serve_react_app(request: Request, full_path: str):
            """Serve the react app
            `full_path` variable is necessary to serve each possible endpoint with
            `index.html` file in order to be compatible with `react-router-dom
            """
            return templates.TemplateResponse("index.html", {"request": request})

        return app