# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chromadb/proto/logservice.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b"\n\x1f\x63hromadb/proto/logservice.proto\x12\x06\x63hroma2\x0c\n\nLogServiceBBZ@github.com/chroma/chroma-coordinator/internal/proto/logservicepbb\x06proto3"
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "chromadb.proto.logservice_pb2", _globals
)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = (
        b"Z@github.com/chroma/chroma-coordinator/internal/proto/logservicepb"
    )
    _globals["_LOGSERVICE"]._serialized_start = 43
    _globals["_LOGSERVICE"]._serialized_end = 55
# @@protoc_insertion_point(module_scope)
