work_queue:
  storage_path: "work-queue/queue.parquet"
  persistence:
    time_threshold_seconds: 5
    pending_threshold: 10

work_queue_service:
  service_name: "work-queue-service"
  my_port: 50051
  otel_endpoint: "http://otel-collector:4317"
  sysdb:
    host: "sysdb.chroma"
    port: 50051
  storage:
    s3:
      bucket: "chroma"
      access_key_id: "minio"
      secret_access_key: "minio123"
      endpoint: "http://minio.chroma.svc.cluster.local:9000"
