import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";

import {SearchEngineContextProvider} from "@/app/contexts/search-engine-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Chroma DB Code Search Demo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="overflow-hidden">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen overflow-y-scroll max-h-screen min-w-screen grid grid-rows-[1fr_4em]`}
      >
        <SearchEngineContextProvider>
          {children}
        </SearchEngineContextProvider>
        <Footer />
      </body>
    </html>
  );
}
