{
 "title": "Chroma Basic",
 "description": "Basic observability dashboard for single-node Chromadb",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "query0", "label": "tqweq" }
  ]
 },
 "panels": [
  { "title": "Core Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "WAL Number of Inserts per Second",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(wal_inserts_count_total{exported_job=\"chroma\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WAL Insert Latency (ms)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max without(thread) (rate(wal_insert_latency_milliseconds_count{exported_job=\"chroma\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Wait Times for HNSW RW Lock (hist)",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 10, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(hnsw_writerwlock_wait_time_milliseconds_count{exported_job=\"chroma\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Segment",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "segment_manager_active_segments_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open Files (count)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_files_count{exported_job=\"chroma\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HNSW Index Write (hist)",
   "type": "histogram",
   "description": "This metric groups the count of calls to the hnsw index _persist method by latency range.\n",
   "gridPos": { "h": 7, "w": 10, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max without(thread) (persistentlocalhnswsegment_persist_milliseconds_sum)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "process_threads_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active Threads",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_threads_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Metadata Index Write (hist)",
   "type": "histogram",
   "description": "This metric groups the count of calls to the metadata index (_write_metadata) method by latency range.",
   "gridPos": { "h": 7, "w": 10, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(sqlitemetadatasegment_write_metadata_milliseconds_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Network Bytes Out",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(network_out_bytes_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Bytes In",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(network_in_bytes_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Time Per Endpoint",
   "type": "piechart",
   "description": "Average response time in milliseconds per endpoint",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(http_target) (rate(http_server_duration_milliseconds_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Times",
   "type": "timeseries",
   "description": "The average overall request response time",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "avg by(http_host) (rate(http_server_duration_milliseconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory and CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "System CPU Usage",
   "type": "timeseries",
   "description": "ChromaDB Python process CPU usage",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(system_cpu_usage_percent{exported_job=\"chroma\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Memory Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(exported_job) (system_memory_usage_percent{exported_job=\"chroma\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Memory Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_memory_usage_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Process VMS Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(process_memory_bytes_vms{exported_job=\"chroma\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process RSS Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(process_memory_bytes_rss{exported_job=\"chroma\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_memory_usage_percent{exported_job=\"chroma\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Log Messages By Level",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (rate({job=\"chroma\"} [24h]))"
    }
   ]
  },
  {
   "title": "Server Logs (All)",
   "type": "logs",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "{job=\"chroma\"} |= ``"
    }
   ]
  }
 ]
}