FROM debian:bookworm-slim

RUN apt update
RUN apt upgrade -y
RUN apt install -y curl
RUN curl -sSf https://atlasgo.sh | sh -s -- --community

COPY ./go/migrations migrations
COPY ./go/atlas.hcl atlas.hcl
