apiVersion: v1
kind: MemberList
metadata:
  name: work-queue-service-memberlist
  namespace: {{ .Values.namespace }}
spec:
  memberSelector:
    matchLabels:
      member-type: work-queue-service
  memberName:
    valueFrom:
      fieldPath: metadata.name
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: work-queue-service-serviceaccount
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: work-queue-service-serviceaccount-rolebinding
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-watcher
subjects:
  - kind: ServiceAccount
    name: work-queue-service-serviceaccount
    namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: work-queue-service-memberlist-readerwriter
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: [""]
    resources: ["memberlists"]
    resourceNames: ["work-queue-service-memberlist"]
    verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: work-queue-service-work-queue-service-memberlist-binding
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: work-queue-service-memberlist-readerwriter
subjects:
  - kind: ServiceAccount
    name: work-queue-service-serviceaccount
    namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: work-queue-service-memberlist-readerwriter-binding
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: work-queue-service-memberlist-readerwriter
subjects:
  - kind: ServiceAccount
    name: work-queue-service-serviceaccount
    namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sysdb-work-queue-service-memberlist-binding
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: work-queue-service-memberlist-readerwriter
subjects:
  - kind: ServiceAccount
    name: sysdb-serviceaccount
    namespace: {{ .Values.namespace }}
