// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// isUpdateSegmentRequest_CollectionUpdate is an autogenerated mock type for the isUpdateSegmentRequest_CollectionUpdate type
type isUpdateSegmentRequest_CollectionUpdate struct {
	mock.Mock
}

// isUpdateSegmentRequest_CollectionUpdate provides a mock function with given fields:
func (_m *isUpdateSegmentRequest_CollectionUpdate) isUpdateSegmentRequest_CollectionUpdate() {
	_m.Called()
}

// newIsUpdateSegmentRequest_CollectionUpdate creates a new instance of isUpdateSegmentRequest_CollectionUpdate. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newIsUpdateSegmentRequest_CollectionUpdate(t interface {
	mock.TestingT
	Cleanup(func())
}) *isUpdateSegmentRequest_CollectionUpdate {
	mock := &isUpdateSegmentRequest_CollectionUpdate{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
