// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeVectorReaderServer is an autogenerated mock type for the UnsafeVectorReaderServer type
type UnsafeVectorReaderServer struct {
	mock.Mock
}

// mustEmbedUnimplementedVectorReaderServer provides a mock function with given fields:
func (_m *UnsafeVectorReaderServer) mustEmbedUnimplementedVectorReaderServer() {
	_m.Called()
}

// NewUnsafeVectorReaderServer creates a new instance of UnsafeVectorReaderServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeVectorReaderServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeVectorReaderServer {
	mock := &UnsafeVectorReaderServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
