// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeLogServiceServer is an autogenerated mock type for the UnsafeLogServiceServer type
type UnsafeLogServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedLogServiceServer provides a mock function with given fields:
func (_m *UnsafeLogServiceServer) mustEmbedUnimplementedLogServiceServer() {
	_m.Called()
}

// NewUnsafeLogServiceServer creates a new instance of UnsafeLogServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeLogServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeLogServiceServer {
	mock := &UnsafeLogServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
