// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/chroma-core/chroma/go/pkg/coordinator/ent/base"
	"github.com/chroma-core/chroma/go/pkg/coordinator/ent/predicate"
)

// BaseUpdate is the builder for updating Base entities.
type BaseUpdate struct {
	config
	hooks    []Hook
	mutation *BaseMutation
}

// Where appends a list predicates to the BaseUpdate builder.
func (bu *BaseUpdate) Where(ps ...predicate.Base) *BaseUpdate {
	bu.mutation.Where(ps...)
	return bu
}

// SetName sets the "name" field.
func (bu *BaseUpdate) SetName(s string) *BaseUpdate {
	bu.mutation.SetName(s)
	return bu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (bu *BaseUpdate) SetNillableName(s *string) *BaseUpdate {
	if s != nil {
		bu.SetName(*s)
	}
	return bu
}

// ClearName clears the value of the "name" field.
func (bu *BaseUpdate) ClearName() *BaseUpdate {
	bu.mutation.ClearName()
	return bu
}

// SetCreatedAt sets the "created_at" field.
func (bu *BaseUpdate) SetCreatedAt(u uint) *BaseUpdate {
	bu.mutation.ResetCreatedAt()
	bu.mutation.SetCreatedAt(u)
	return bu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (bu *BaseUpdate) SetNillableCreatedAt(u *uint) *BaseUpdate {
	if u != nil {
		bu.SetCreatedAt(*u)
	}
	return bu
}

// AddCreatedAt adds u to the "created_at" field.
func (bu *BaseUpdate) AddCreatedAt(u int) *BaseUpdate {
	bu.mutation.AddCreatedAt(u)
	return bu
}

// SetUpdatedAt sets the "updated_at" field.
func (bu *BaseUpdate) SetUpdatedAt(u uint) *BaseUpdate {
	bu.mutation.ResetUpdatedAt()
	bu.mutation.SetUpdatedAt(u)
	return bu
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (bu *BaseUpdate) SetNillableUpdatedAt(u *uint) *BaseUpdate {
	if u != nil {
		bu.SetUpdatedAt(*u)
	}
	return bu
}

// AddUpdatedAt adds u to the "updated_at" field.
func (bu *BaseUpdate) AddUpdatedAt(u int) *BaseUpdate {
	bu.mutation.AddUpdatedAt(u)
	return bu
}

// SetDeletedAt sets the "deleted_at" field.
func (bu *BaseUpdate) SetDeletedAt(u uint) *BaseUpdate {
	bu.mutation.ResetDeletedAt()
	bu.mutation.SetDeletedAt(u)
	return bu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (bu *BaseUpdate) SetNillableDeletedAt(u *uint) *BaseUpdate {
	if u != nil {
		bu.SetDeletedAt(*u)
	}
	return bu
}

// AddDeletedAt adds u to the "deleted_at" field.
func (bu *BaseUpdate) AddDeletedAt(u int) *BaseUpdate {
	bu.mutation.AddDeletedAt(u)
	return bu
}

// SetVersion sets the "version" field.
func (bu *BaseUpdate) SetVersion(i int) *BaseUpdate {
	bu.mutation.ResetVersion()
	bu.mutation.SetVersion(i)
	return bu
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (bu *BaseUpdate) SetNillableVersion(i *int) *BaseUpdate {
	if i != nil {
		bu.SetVersion(*i)
	}
	return bu
}

// AddVersion adds i to the "version" field.
func (bu *BaseUpdate) AddVersion(i int) *BaseUpdate {
	bu.mutation.AddVersion(i)
	return bu
}

// Mutation returns the BaseMutation object of the builder.
func (bu *BaseUpdate) Mutation() *BaseMutation {
	return bu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (bu *BaseUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, bu.sqlSave, bu.mutation, bu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (bu *BaseUpdate) SaveX(ctx context.Context) int {
	affected, err := bu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (bu *BaseUpdate) Exec(ctx context.Context) error {
	_, err := bu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bu *BaseUpdate) ExecX(ctx context.Context) {
	if err := bu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bu *BaseUpdate) check() error {
	if v, ok := bu.mutation.Name(); ok {
		if err := base.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Base.name": %w`, err)}
		}
	}
	return nil
}

func (bu *BaseUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := bu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(base.Table, base.Columns, sqlgraph.NewFieldSpec(base.FieldID, field.TypeUUID))
	if ps := bu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := bu.mutation.Name(); ok {
		_spec.SetField(base.FieldName, field.TypeString, value)
	}
	if bu.mutation.NameCleared() {
		_spec.ClearField(base.FieldName, field.TypeString)
	}
	if value, ok := bu.mutation.CreatedAt(); ok {
		_spec.SetField(base.FieldCreatedAt, field.TypeUint, value)
	}
	if value, ok := bu.mutation.AddedCreatedAt(); ok {
		_spec.AddField(base.FieldCreatedAt, field.TypeUint, value)
	}
	if value, ok := bu.mutation.UpdatedAt(); ok {
		_spec.SetField(base.FieldUpdatedAt, field.TypeUint, value)
	}
	if value, ok := bu.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(base.FieldUpdatedAt, field.TypeUint, value)
	}
	if value, ok := bu.mutation.DeletedAt(); ok {
		_spec.SetField(base.FieldDeletedAt, field.TypeUint, value)
	}
	if value, ok := bu.mutation.AddedDeletedAt(); ok {
		_spec.AddField(base.FieldDeletedAt, field.TypeUint, value)
	}
	if value, ok := bu.mutation.Version(); ok {
		_spec.SetField(base.FieldVersion, field.TypeInt, value)
	}
	if value, ok := bu.mutation.AddedVersion(); ok {
		_spec.AddField(base.FieldVersion, field.TypeInt, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, bu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{base.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	bu.mutation.done = true
	return n, nil
}

// BaseUpdateOne is the builder for updating a single Base entity.
type BaseUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BaseMutation
}

// SetName sets the "name" field.
func (buo *BaseUpdateOne) SetName(s string) *BaseUpdateOne {
	buo.mutation.SetName(s)
	return buo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (buo *BaseUpdateOne) SetNillableName(s *string) *BaseUpdateOne {
	if s != nil {
		buo.SetName(*s)
	}
	return buo
}

// ClearName clears the value of the "name" field.
func (buo *BaseUpdateOne) ClearName() *BaseUpdateOne {
	buo.mutation.ClearName()
	return buo
}

// SetCreatedAt sets the "created_at" field.
func (buo *BaseUpdateOne) SetCreatedAt(u uint) *BaseUpdateOne {
	buo.mutation.ResetCreatedAt()
	buo.mutation.SetCreatedAt(u)
	return buo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (buo *BaseUpdateOne) SetNillableCreatedAt(u *uint) *BaseUpdateOne {
	if u != nil {
		buo.SetCreatedAt(*u)
	}
	return buo
}

// AddCreatedAt adds u to the "created_at" field.
func (buo *BaseUpdateOne) AddCreatedAt(u int) *BaseUpdateOne {
	buo.mutation.AddCreatedAt(u)
	return buo
}

// SetUpdatedAt sets the "updated_at" field.
func (buo *BaseUpdateOne) SetUpdatedAt(u uint) *BaseUpdateOne {
	buo.mutation.ResetUpdatedAt()
	buo.mutation.SetUpdatedAt(u)
	return buo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (buo *BaseUpdateOne) SetNillableUpdatedAt(u *uint) *BaseUpdateOne {
	if u != nil {
		buo.SetUpdatedAt(*u)
	}
	return buo
}

// AddUpdatedAt adds u to the "updated_at" field.
func (buo *BaseUpdateOne) AddUpdatedAt(u int) *BaseUpdateOne {
	buo.mutation.AddUpdatedAt(u)
	return buo
}

// SetDeletedAt sets the "deleted_at" field.
func (buo *BaseUpdateOne) SetDeletedAt(u uint) *BaseUpdateOne {
	buo.mutation.ResetDeletedAt()
	buo.mutation.SetDeletedAt(u)
	return buo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (buo *BaseUpdateOne) SetNillableDeletedAt(u *uint) *BaseUpdateOne {
	if u != nil {
		buo.SetDeletedAt(*u)
	}
	return buo
}

// AddDeletedAt adds u to the "deleted_at" field.
func (buo *BaseUpdateOne) AddDeletedAt(u int) *BaseUpdateOne {
	buo.mutation.AddDeletedAt(u)
	return buo
}

// SetVersion sets the "version" field.
func (buo *BaseUpdateOne) SetVersion(i int) *BaseUpdateOne {
	buo.mutation.ResetVersion()
	buo.mutation.SetVersion(i)
	return buo
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (buo *BaseUpdateOne) SetNillableVersion(i *int) *BaseUpdateOne {
	if i != nil {
		buo.SetVersion(*i)
	}
	return buo
}

// AddVersion adds i to the "version" field.
func (buo *BaseUpdateOne) AddVersion(i int) *BaseUpdateOne {
	buo.mutation.AddVersion(i)
	return buo
}

// Mutation returns the BaseMutation object of the builder.
func (buo *BaseUpdateOne) Mutation() *BaseMutation {
	return buo.mutation
}

// Where appends a list predicates to the BaseUpdate builder.
func (buo *BaseUpdateOne) Where(ps ...predicate.Base) *BaseUpdateOne {
	buo.mutation.Where(ps...)
	return buo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (buo *BaseUpdateOne) Select(field string, fields ...string) *BaseUpdateOne {
	buo.fields = append([]string{field}, fields...)
	return buo
}

// Save executes the query and returns the updated Base entity.
func (buo *BaseUpdateOne) Save(ctx context.Context) (*Base, error) {
	return withHooks(ctx, buo.sqlSave, buo.mutation, buo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (buo *BaseUpdateOne) SaveX(ctx context.Context) *Base {
	node, err := buo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (buo *BaseUpdateOne) Exec(ctx context.Context) error {
	_, err := buo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (buo *BaseUpdateOne) ExecX(ctx context.Context) {
	if err := buo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (buo *BaseUpdateOne) check() error {
	if v, ok := buo.mutation.Name(); ok {
		if err := base.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Base.name": %w`, err)}
		}
	}
	return nil
}

func (buo *BaseUpdateOne) sqlSave(ctx context.Context) (_node *Base, err error) {
	if err := buo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(base.Table, base.Columns, sqlgraph.NewFieldSpec(base.FieldID, field.TypeUUID))
	id, ok := buo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Base.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := buo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, base.FieldID)
		for _, f := range fields {
			if !base.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != base.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := buo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := buo.mutation.Name(); ok {
		_spec.SetField(base.FieldName, field.TypeString, value)
	}
	if buo.mutation.NameCleared() {
		_spec.ClearField(base.FieldName, field.TypeString)
	}
	if value, ok := buo.mutation.CreatedAt(); ok {
		_spec.SetField(base.FieldCreatedAt, field.TypeUint, value)
	}
	if value, ok := buo.mutation.AddedCreatedAt(); ok {
		_spec.AddField(base.FieldCreatedAt, field.TypeUint, value)
	}
	if value, ok := buo.mutation.UpdatedAt(); ok {
		_spec.SetField(base.FieldUpdatedAt, field.TypeUint, value)
	}
	if value, ok := buo.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(base.FieldUpdatedAt, field.TypeUint, value)
	}
	if value, ok := buo.mutation.DeletedAt(); ok {
		_spec.SetField(base.FieldDeletedAt, field.TypeUint, value)
	}
	if value, ok := buo.mutation.AddedDeletedAt(); ok {
		_spec.AddField(base.FieldDeletedAt, field.TypeUint, value)
	}
	if value, ok := buo.mutation.Version(); ok {
		_spec.SetField(base.FieldVersion, field.TypeInt, value)
	}
	if value, ok := buo.mutation.AddedVersion(); ok {
		_spec.AddField(base.FieldVersion, field.TypeInt, value)
	}
	_node = &Base{config: buo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, buo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{base.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	buo.mutation.done = true
	return _node, nil
}
