// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/chroma-core/chroma/go/pkg/coordinator/ent/base"
	"github.com/google/uuid"
)

// BaseCreate is the builder for creating a Base entity.
type BaseCreate struct {
	config
	mutation *BaseMutation
	hooks    []Hook
}

// SetParentID sets the "parent_id" field.
func (bc *BaseCreate) SetParentID(u uuid.UUID) *BaseCreate {
	bc.mutation.SetParentID(u)
	return bc
}

// SetName sets the "name" field.
func (bc *BaseCreate) SetName(s string) *BaseCreate {
	bc.mutation.SetName(s)
	return bc
}

// SetNillableName sets the "name" field if the given value is not nil.
func (bc *BaseCreate) SetNillableName(s *string) *BaseCreate {
	if s != nil {
		bc.SetName(*s)
	}
	return bc
}

// SetCreatedAt sets the "created_at" field.
func (bc *BaseCreate) SetCreatedAt(u uint) *BaseCreate {
	bc.mutation.SetCreatedAt(u)
	return bc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (bc *BaseCreate) SetNillableCreatedAt(u *uint) *BaseCreate {
	if u != nil {
		bc.SetCreatedAt(*u)
	}
	return bc
}

// SetUpdatedAt sets the "updated_at" field.
func (bc *BaseCreate) SetUpdatedAt(u uint) *BaseCreate {
	bc.mutation.SetUpdatedAt(u)
	return bc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (bc *BaseCreate) SetNillableUpdatedAt(u *uint) *BaseCreate {
	if u != nil {
		bc.SetUpdatedAt(*u)
	}
	return bc
}

// SetDeletedAt sets the "deleted_at" field.
func (bc *BaseCreate) SetDeletedAt(u uint) *BaseCreate {
	bc.mutation.SetDeletedAt(u)
	return bc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (bc *BaseCreate) SetNillableDeletedAt(u *uint) *BaseCreate {
	if u != nil {
		bc.SetDeletedAt(*u)
	}
	return bc
}

// SetVersion sets the "version" field.
func (bc *BaseCreate) SetVersion(i int) *BaseCreate {
	bc.mutation.SetVersion(i)
	return bc
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (bc *BaseCreate) SetNillableVersion(i *int) *BaseCreate {
	if i != nil {
		bc.SetVersion(*i)
	}
	return bc
}

// SetID sets the "id" field.
func (bc *BaseCreate) SetID(u uuid.UUID) *BaseCreate {
	bc.mutation.SetID(u)
	return bc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (bc *BaseCreate) SetNillableID(u *uuid.UUID) *BaseCreate {
	if u != nil {
		bc.SetID(*u)
	}
	return bc
}

// Mutation returns the BaseMutation object of the builder.
func (bc *BaseCreate) Mutation() *BaseMutation {
	return bc.mutation
}

// Save creates the Base in the database.
func (bc *BaseCreate) Save(ctx context.Context) (*Base, error) {
	bc.defaults()
	return withHooks(ctx, bc.sqlSave, bc.mutation, bc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (bc *BaseCreate) SaveX(ctx context.Context) *Base {
	v, err := bc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bc *BaseCreate) Exec(ctx context.Context) error {
	_, err := bc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bc *BaseCreate) ExecX(ctx context.Context) {
	if err := bc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (bc *BaseCreate) defaults() {
	if _, ok := bc.mutation.CreatedAt(); !ok {
		v := base.DefaultCreatedAt()
		bc.mutation.SetCreatedAt(v)
	}
	if _, ok := bc.mutation.UpdatedAt(); !ok {
		v := base.DefaultUpdatedAt()
		bc.mutation.SetUpdatedAt(v)
	}
	if _, ok := bc.mutation.DeletedAt(); !ok {
		v := base.DefaultDeletedAt
		bc.mutation.SetDeletedAt(v)
	}
	if _, ok := bc.mutation.Version(); !ok {
		v := base.DefaultVersion
		bc.mutation.SetVersion(v)
	}
	if _, ok := bc.mutation.ID(); !ok {
		v := base.DefaultID()
		bc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bc *BaseCreate) check() error {
	if _, ok := bc.mutation.ParentID(); !ok {
		return &ValidationError{Name: "parent_id", err: errors.New(`ent: missing required field "Base.parent_id"`)}
	}
	if v, ok := bc.mutation.Name(); ok {
		if err := base.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Base.name": %w`, err)}
		}
	}
	if _, ok := bc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Base.created_at"`)}
	}
	if _, ok := bc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Base.updated_at"`)}
	}
	if _, ok := bc.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`ent: missing required field "Base.deleted_at"`)}
	}
	if _, ok := bc.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "Base.version"`)}
	}
	return nil
}

func (bc *BaseCreate) sqlSave(ctx context.Context) (*Base, error) {
	if err := bc.check(); err != nil {
		return nil, err
	}
	_node, _spec := bc.createSpec()
	if err := sqlgraph.CreateNode(ctx, bc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	bc.mutation.id = &_node.ID
	bc.mutation.done = true
	return _node, nil
}

func (bc *BaseCreate) createSpec() (*Base, *sqlgraph.CreateSpec) {
	var (
		_node = &Base{config: bc.config}
		_spec = sqlgraph.NewCreateSpec(base.Table, sqlgraph.NewFieldSpec(base.FieldID, field.TypeUUID))
	)
	if id, ok := bc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := bc.mutation.ParentID(); ok {
		_spec.SetField(base.FieldParentID, field.TypeUUID, value)
		_node.ParentID = value
	}
	if value, ok := bc.mutation.Name(); ok {
		_spec.SetField(base.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := bc.mutation.CreatedAt(); ok {
		_spec.SetField(base.FieldCreatedAt, field.TypeUint, value)
		_node.CreatedAt = value
	}
	if value, ok := bc.mutation.UpdatedAt(); ok {
		_spec.SetField(base.FieldUpdatedAt, field.TypeUint, value)
		_node.UpdatedAt = value
	}
	if value, ok := bc.mutation.DeletedAt(); ok {
		_spec.SetField(base.FieldDeletedAt, field.TypeUint, value)
		_node.DeletedAt = value
	}
	if value, ok := bc.mutation.Version(); ok {
		_spec.SetField(base.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	return _node, _spec
}

// BaseCreateBulk is the builder for creating many Base entities in bulk.
type BaseCreateBulk struct {
	config
	err      error
	builders []*BaseCreate
}

// Save creates the Base entities in the database.
func (bcb *BaseCreateBulk) Save(ctx context.Context) ([]*Base, error) {
	if bcb.err != nil {
		return nil, bcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(bcb.builders))
	nodes := make([]*Base, len(bcb.builders))
	mutators := make([]Mutator, len(bcb.builders))
	for i := range bcb.builders {
		func(i int, root context.Context) {
			builder := bcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BaseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, bcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, bcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, bcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (bcb *BaseCreateBulk) SaveX(ctx context.Context) []*Base {
	v, err := bcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bcb *BaseCreateBulk) Exec(ctx context.Context) error {
	_, err := bcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bcb *BaseCreateBulk) ExecX(ctx context.Context) {
	if err := bcb.Exec(ctx); err != nil {
		panic(err)
	}
}
