// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/chroma-core/chroma/go/pkg/coordinator/ent/base"
	"github.com/chroma-core/chroma/go/pkg/coordinator/ent/schema"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	baseFields := schema.Base{}.Fields()
	_ = baseFields
	// baseDescName is the schema descriptor for name field.
	baseDescName := baseFields[2].Descriptor()
	// base.NameValidator is a validator for the "name" field. It is called by the builders before save.
	base.NameValidator = baseDescName.Validators[0].(func(string) error)
	// baseDescCreatedAt is the schema descriptor for created_at field.
	baseDescCreatedAt := baseFields[3].Descriptor()
	// base.DefaultCreatedAt holds the default value on creation for the created_at field.
	base.DefaultCreatedAt = baseDescCreatedAt.Default.(func() uint)
	// baseDescUpdatedAt is the schema descriptor for updated_at field.
	baseDescUpdatedAt := baseFields[4].Descriptor()
	// base.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	base.DefaultUpdatedAt = baseDescUpdatedAt.Default.(func() uint)
	// baseDescDeletedAt is the schema descriptor for deleted_at field.
	baseDescDeletedAt := baseFields[5].Descriptor()
	// base.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	base.DefaultDeletedAt = baseDescDeletedAt.Default.(uint)
	// baseDescVersion is the schema descriptor for version field.
	baseDescVersion := baseFields[6].Descriptor()
	// base.DefaultVersion holds the default value on creation for the version field.
	base.DefaultVersion = baseDescVersion.Default.(int)
	// baseDescID is the schema descriptor for id field.
	baseDescID := baseFields[1].Descriptor()
	// base.DefaultID holds the default value on creation for the id field.
	base.DefaultID = baseDescID.Default.(func() uuid.UUID)
}
