// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/chroma-core/chroma/go/pkg/coordinator/ent/testbase"
)

// TestBase is the model entity for the TestBase schema.
type TestBase struct {
	config
	// ID of the ent.
	ID           int `json:"id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TestBase) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case testbase.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TestBase fields.
func (tb *TestBase) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case testbase.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			tb.ID = int(value.Int64)
		default:
			tb.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TestBase.
// This includes values selected through modifiers, order, etc.
func (tb *TestBase) Value(name string) (ent.Value, error) {
	return tb.selectValues.Get(name)
}

// Update returns a builder for updating this TestBase.
// Note that you need to call TestBase.Unwrap() before calling this method if this TestBase
// was returned from a transaction, and the transaction was committed or rolled back.
func (tb *TestBase) Update() *TestBaseUpdateOne {
	return NewTestBaseClient(tb.config).UpdateOne(tb)
}

// Unwrap unwraps the TestBase entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (tb *TestBase) Unwrap() *TestBase {
	_tx, ok := tb.config.driver.(*txDriver)
	if !ok {
		panic("ent: TestBase is not a transactional entity")
	}
	tb.config.driver = _tx.drv
	return tb
}

// String implements the fmt.Stringer.
func (tb *TestBase) String() string {
	var builder strings.Builder
	builder.WriteString("TestBase(")
	builder.WriteString(fmt.Sprintf("id=%v", tb.ID))
	builder.WriteByte(')')
	return builder.String()
}

// TestBases is a parsable slice of TestBase.
type TestBases []*TestBase
