// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Base is the predicate function for base builders.
type Base func(*sql.Selector)

// TestBase is the predicate function for testbase builders.
type TestBase func(*sql.Selector)
